name 'maestrodev-continuum'
version '0.0.1'

author 'maestrodev'
license 'Apache License, Version 2.0'
project_page 'http://github.com/maestrodev/puppet-continuum'
source 'http://github.com/maestrodev/puppet-continuum'
summary 'Apache Continuum module for Puppet'
description 'A Puppet module to install Continuum and its build agents'
dependency 'maestrodev/wget', '>=0.0.1'
dependency 'maestrodev/maven', '>=0.0.2'
